[package]
name = "pftp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
byteorder = "1"
sha2 = "0.10"
rand = "0.8"

[dev-dependencies]
tempfile = "3"
